Repository problem-not-found/artium-be, pull requests merged in 2025-08, with the labels that each got.

#19 ♻️Refactor: 코드 리뷰 기반 수정사항 반영
  .github/workflows/cd.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/likelion13/artium/domain/auth/controller/AuthController.java
  src/main/java/com/likelion13/artium/domain/user/controller/UserController.java
  src/main/java/com/likelion13/artium/domain/user/controller/UserControllerImpl.java
  src/main/java/com/likelion13/artium/domain/user/dto/response/LikeResponse.java
  src/main/java/com/likelion13/artium/domain/user/dto/response/UserDetailResponse.java
  src/main/java/com/likelion13/artium/domain/user/entity/User.java
  src/main/java/com/likelion13/artium/domain/user/exception/UserErrorCode.java
  src/main/java/com/likelion13/artium/domain/user/mapper/UserMapper.java
  src/main/java/com/likelion13/artium/domain/user/mapping/UserLike.java
  src/main/java/com/likelion13/artium/domain/user/repository/UserRepository.java
  src/main/java/com/likelion13/artium/domain/user/service/UserService.java
  src/main/java/com/likelion13/artium/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion13/artium/global/config/CorsConfig.java
  src/main/java/com/likelion13/artium/global/jwt/JwtProvider.java
  src/main/java/com/likelion13/artium/global/jwt/TokenRepository.java
Labels: 🐞 bug

#26 :bug:Fix: 이미지 이름 수정
  docker-compose.yml
Labels: 🐞 bug

#29 ✨Feat: Exhibition 관련 좋아요 기능 생성
  .github/workflows/cd.yml
  .gitignore
  src/main/java/com/likelion13/artium/domain/exhibition/controller/ExhibitionController.java
  src/main/java/com/likelion13/artium/domain/exhibition/controller/ExhibitionControllerImpl.java
  src/main/java/com/likelion13/artium/domain/exhibition/dto/response/ExhibitionLikeResponse.java
  src/main/java/com/likelion13/artium/domain/exhibition/exception/ExhibitionErrorCode.java
  src/main/java/com/likelion13/artium/domain/exhibition/mapper/ExhibitionMapper.java
  src/main/java/com/likelion13/artium/domain/exhibition/mapping/ExhibitionLike.java
  src/main/java/com/likelion13/artium/domain/exhibition/repository/ExhibitionLikeRepository.java
  src/main/java/com/likelion13/artium/domain/exhibition/repository/ExhibitionParticipantRepository.java
  src/main/java/com/likelion13/artium/domain/exhibition/repository/ExhibitionRepository.java
  src/main/java/com/likelion13/artium/domain/exhibition/service/ExhibitionService.java
  src/main/java/com/likelion13/artium/domain/exhibition/service/ExhibitionServiceImpl.java
  src/main/java/com/likelion13/artium/domain/user/controller/UserController.java
  src/main/java/com/likelion13/artium/domain/user/controller/UserControllerImpl.java
  src/main/java/com/likelion13/artium/domain/user/dto/response/UserLikeResponse.java
  src/main/java/com/likelion13/artium/domain/user/mapper/UserMapper.java
  src/main/java/com/likelion13/artium/domain/user/repository/UserLikeRepository.java
  src/main/java/com/likelion13/artium/domain/user/service/UserService.java
  src/main/java/com/likelion13/artium/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion13/artium/global/config/SecurityConfig.java
Labels: ✨ feature, 👀 review needed, 🔴 priority: high

#32 ♻️Refactor: 전시 관련 API 1차 리팩토링
  docker-compose.yml
  src/main/java/com/likelion13/artium/domain/auth/controller/AuthController.java
  src/main/java/com/likelion13/artium/domain/auth/controller/AuthControllerImpl.java
  src/main/java/com/likelion13/artium/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/likelion13/artium/domain/auth/service/AuthService.java
  src/main/java/com/likelion13/artium/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/likelion13/artium/domain/exhibition/controller/ExhibitionController.java
  src/main/java/com/likelion13/artium/domain/exhibition/controller/ExhibitionControllerImpl.java
  src/main/java/com/likelion13/artium/domain/exhibition/dto/request/ExhibitionRequest.java
  src/main/java/com/likelion13/artium/domain/exhibition/dto/response/ExhibitionDetailResponse.java
  src/main/java/com/likelion13/artium/domain/exhibition/entity/Exhibition.java
  src/main/java/com/likelion13/artium/domain/exhibition/exception/ExhibitionErrorCode.java
  src/main/java/com/likelion13/artium/domain/exhibition/mapper/ExhibitionMapper.java
  src/main/java/com/likelion13/artium/domain/exhibition/service/ExhibitionService.java
  src/main/java/com/likelion13/artium/domain/exhibition/service/ExhibitionServiceImpl.java
  src/main/java/com/likelion13/artium/domain/piece/entity/Piece.java
  src/main/java/com/likelion13/artium/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/likelion13/artium/domain/review/mapper/ReviewMapper.java
  src/main/java/com/likelion13/artium/global/config/SecurityConfig.java
  src/main/java/com/likelion13/artium/global/exception/GlobalExceptionHandler.java
  src/main/java/com/likelion13/artium/global/jwt/JwtProvider.java
  src/main/java/com/likelion13/artium/global/jwt/TokenRepository.java
  src/main/java/com/likelion13/artium/global/security/JwtAuthenticationFilter.java
Labels: ✨ feature, ♻️ refactor

#34 ♻️ Refactor: 작품 기능 세부사항 리팩토링
  src/main/java/com/likelion13/artium/domain/piece/controller/PieceController.java
  src/main/java/com/likelion13/artium/domain/piece/controller/PieceControllerImpl.java
  src/main/java/com/likelion13/artium/domain/piece/dto/response/PieceFeedResponse.java
  src/main/java/com/likelion13/artium/domain/piece/exception/PieceErrorCode.java
  src/main/java/com/likelion13/artium/domain/piece/mapper/PieceMapper.java
  src/main/java/com/likelion13/artium/domain/piece/repository/PieceRepository.java
  src/main/java/com/likelion13/artium/domain/piece/service/PieceService.java
  src/main/java/com/likelion13/artium/domain/piece/service/PieceServiceImpl.java
  src/main/java/com/likelion13/artium/domain/pieceDetail/service/PieceDetailServiceImpl.java
  src/main/java/com/likelion13/artium/domain/pieceLike/controller/PieceLikeController.java
  src/main/java/com/likelion13/artium/domain/pieceLike/controller/PieceLikeControllerImpl.java
  src/main/java/com/likelion13/artium/domain/pieceLike/exception/PieceLikeErrorCode.java
  src/main/java/com/likelion13/artium/domain/pieceLike/repository/PieceLikeRepository.java
  src/main/java/com/likelion13/artium/domain/pieceLike/service/PieceLikeServiceImpl.java
  src/main/java/com/likelion13/artium/global/page/mapper/PageMapper.java
Labels: ♻️ refactor, 👀 review needed, 🔴 priority: high

#39 :sparkles: Feat: 관심사 기반 작품 추천 기능 추가 및 보완
  src/main/java/com/likelion13/artium/domain/exhibition/dto/response/ExhibitionSummaryResponse.java
  src/main/java/com/likelion13/artium/domain/exhibition/entity/Exhibition.java
  src/main/java/com/likelion13/artium/domain/exhibition/mapper/ExhibitionMapper.java
  src/main/java/com/likelion13/artium/domain/exhibition/mapping/ExhibitionPiece.java
  src/main/java/com/likelion13/artium/domain/exhibition/repository/ExhibitionPieceRepository.java
  src/main/java/com/likelion13/artium/domain/exhibition/service/ExhibitionServiceImpl.java
  src/main/java/com/likelion13/artium/domain/piece/controller/PieceController.java
  src/main/java/com/likelion13/artium/domain/piece/controller/PieceControllerImpl.java
  src/main/java/com/likelion13/artium/domain/piece/dto/response/PieceResponse.java
  src/main/java/com/likelion13/artium/domain/piece/entity/Piece.java
  src/main/java/com/likelion13/artium/domain/piece/entity/RecommendSortBy.java
  src/main/java/com/likelion13/artium/domain/piece/mapper/PieceMapper.java
  src/main/java/com/likelion13/artium/domain/piece/repository/PieceRepository.java
  src/main/java/com/likelion13/artium/domain/piece/service/PieceService.java
  src/main/java/com/likelion13/artium/domain/piece/service/PieceServiceImpl.java
  src/main/java/com/likelion13/artium/domain/user/controller/UserControllerImpl.java
  src/main/java/com/likelion13/artium/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion13/artium/global/ai/vector/VectorUtils.java
  src/main/java/com/likelion13/artium/global/qdrant/service/QdrantServiceImpl.java
Labels: ✨ feature, 👀 review needed, 🟠 priority: medium

#42 ♻️Refactor: 추천 전시 조회 성능 개선
  .github/workflows/cd.yml
  src/main/java/com/likelion13/artium/domain/exhibition/service/ExhibitionServiceImpl.java
  src/main/java/com/likelion13/artium/global/config/SecurityConfig.java
  src/main/java/com/likelion13/artium/global/exception/GlobalExceptionHandler.java
  src/main/java/com/likelion13/artium/global/jwt/JwtProvider.java
  src/main/java/com/likelion13/artium/global/security/JwtAuthenticationFilter.java
Labels: ♻️ refactor, 🧹 chore, 🟠 priority: medium

#46 🐛Fix: 오류 수정
  .github/workflows/cd.yml
  docker/docker-compose-dev.yml
  docker/docker-compose.yml
Labels: 🧹 chore

#47 🐛Fix: Blue-Green 서버 오류 수정
  .github/workflows/cd.yml
Labels: 🐞 bug

#49 🐛Fix: Blue-Green 네트워크 오류 수정
  .github/workflows/cd.yml
Labels: 🐞 bug

#50 🐛Fix: Blue-Green 네트워크 오류 수정
  .github/workflows/cd.yml
Labels: 🐞 bug

#60 🐛Fix: 전시 수정 오류 수정
  src/main/java/com/likelion13/artium/domain/exhibition/service/ExhibitionServiceImpl.java
Labels: 🐞 bug

#62 ♻️Refactor: 지금 뜨는 크리에이터 코드 추가
  src/main/java/com/likelion13/artium/domain/exhibition/service/ExhibitionServiceImpl.java
  src/main/java/com/likelion13/artium/domain/piece/service/PieceServiceImpl.java
  src/main/java/com/likelion13/artium/domain/user/controller/UserController.java
  src/main/java/com/likelion13/artium/domain/user/dto/response/CreatorFeedResponse.java
  src/main/java/com/likelion13/artium/domain/user/mapper/UserMapper.java
  src/main/java/com/likelion13/artium/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion13/artium/global/qdrant/service/QdrantService.java
  src/main/java/com/likelion13/artium/global/qdrant/service/QdrantServiceImpl.java
Labels: 🐞 bug
